### ISSUE TITLE
[EngAut] TipBot improvements

### ISSUE THREAD

**Issue by mordamax** [paritytech/substrate-tip-bot#137]
### Goal
Keep incentivise external contributors to deliver excellent work

There's some tech debt & improvements for this bot
```[tasklist]
### Tasks
- [ ] https://github.com/paritytech/substrate-tip-bot/pull/136
- [ ] https://github.com/paritytech/substrate-tip-bot/issues/113
- [ ] https://github.com/paritytech/substrate-tip-bot/issues/46
- [ ] https://github.com/paritytech/substrate-tip-bot/issues/145
```

**Comment by rzadp** [comment]
Status update:
- Restored Polkassembly integration after a breaking change in the API: https://github.com/paritytech/substrate-tip-bot/issues/132
- Periodically keep Polkadot build cache warm in order to support infrequent PRs: https://github.com/paritytech/substrate-tip-bot/pull/136

**Comment by rzadp** [comment]
No updates this week.

**Comment by rzadp** [comment]
Updates:

- [Updated the code](https://github.com/paritytech/substrate-tip-bot/pull/144) after a breaking change in a Polkadot release.
  - Updated the integration and E2E tests to run against a most recent `v1.7.1` release.
- Proposed a [weekly job](https://github.com/paritytech/substrate-tip-bot/pull/147) that will test the code against a most recent Polkadot release, in order to catch errors (like the one above) much earlier, before the release is applied in the runtimes.
- The bot will post a link to Polkassembly in the PR - https://github.com/paritytech/substrate-tip-bot/pull/141.
- Support testnets - Added Rococo and Westend testnets.

**Comment by rzadp** [comment]
One [PR](https://github.com/paritytech/substrate-tip-bot/pull/147) is unmerged, but other than that the work is done here.
