### ISSUE TITLE
Store tip metadata through `set_metadata` instead of a remark

### ISSUE THREAD

**Issue by rzadp** [paritytech/substrate-tip-bot#74]
Remark is not possible at the moment and breaks the referenda.
(But might be possible after https://github.com/paritytech/substrate/pull/14260). Still, metadata is preferred.

```[tasklist]
### Tasks
- [x] Fix & Deploy referenda
- [x] Reapply https://kusama.polkassembly.io/referenda/205 -> https://github.com/paritytech/substrate/pull/13993,
- [x] Reapply https://kusama.polkassembly.io/referenda/206 -> https://github.com/paritytech/substrate/pull/13027,
- [x] Reapply https://kusama.polkassembly.io/referenda/207 -> https://github.com/paritytech/cumulus/pull/2294
- [x] In each new referenda, on polkassembly, leave a comment that it's re-submitting a tip for according PR due to this issue
```

**Comment by rzadp** [comment]
New referenda:

- https://kusama.polkassembly.io/referenda/216
- https://kusama.polkassembly.io/referenda/217
- https://kusama.polkassembly.io/referenda/218

cc @mordamax

**Comment by rzadp** [comment]
Solved by https://github.com/paritytech/substrate-tip-bot/pull/79
