### ISSUE TITLE
[EngAut]: Tip Bot Improvements

### ISSUE THREAD

**Issue by mordamax** [paritytech/substrate-tip-bot#78]
**Goal**: To improve the user-experience when tipping or receiving tips for contributions.

---

```[tasklist]
### Tasks
- [ ] https://github.com/paritytech/substrate-tip-bot/issues/39
- [ ] https://github.com/paritytech/substrate-tip-bot/issues/86
- [ ] https://github.com/paritytech/substrate-tip-bot/issues/62
- [ ] https://github.com/paritytech/substrate-tip-bot/issues/74
- [ ] https://github.com/paritytech/substrate-tip-bot/issues/65
- [ ] https://github.com/paritytech/substrate-tip-bot/issues/73
- [ ] https://github.com/paritytech/substrate-tip-bot/issues/76
- [ ] https://github.com/paritytech/substrate-tip-bot/issues/11
- [ ] https://github.com/paritytech/substrate-tip-bot/issues/54
- [ ] https://github.com/paritytech/substrate-tip-bot/issues/84
- [ ] https://github.com/paritytech/substrate-tip-bot/issues/85
- [ ] https://github.com/paritytech/substrate-tip-bot/issues/69
```
